import "./globals.css";
import type { Metadata } from "next";
import { headers } from "next/headers";
import { Inter as FontSans } from "next/font/google";
import { cookieToInitialState } from "wagmi";

import { config } from "@/config/web3modal";
import Web3ModalProvider from "@/context/web3modal";
import { cn } from "@/lib/utils";
import { ThemeProvider } from "@/context/theme";
import { SolanaWalletProvider } from "@/context/SolanaWalletProvider";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const initialState = cookieToInitialState(config, headers().get("cookie"));
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        <ThemeProvider attribute="class" defaultTheme="dark">
          <Web3ModalProvider initialState={initialState}>
            <SolanaWalletProvider>{children}</SolanaWalletProvider>
          </Web3ModalProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
